// StyleTypes+Generable.swift
// Foundation Models @Generable types for style analysis

import Foundation
import FoundationModels

// MARK: - @Generable Types for Foundation Models

/// A style improvement suggestion generated by Foundation Models
@available(macOS 26.0, *)
@Generable
struct FMStyleSuggestion {
    @Guide(description: """
        The exact phrase from the input text that should be improved.
        Must be a verbatim substring - character-for-character match.
        """)
    let original: String

    @Guide(description: """
        The improved version of the phrase.
        Must maintain the same meaning while improving style.
        """)
    let suggested: String

    @Guide(description: """
        Brief explanation (1-2 sentences) of why this change improves the text.
        Focus on the specific improvement, not generic advice.
        """)
    let explanation: String
}

/// Result of Foundation Models style analysis
@available(macOS 26.0, *)
@Generable
struct FMStyleAnalysisResult {
    @Guide(description: """
        List of style improvement suggestions.
        Return empty array [] if the text is already well-written.
        Order by impact (most important first).
        Maximum 5 suggestions per analysis.
        """)
    let suggestions: [FMStyleSuggestion]
}

// MARK: - Conversion to App Types

@available(macOS 26.0, *)
extension FMStyleSuggestion {
    /// Convert to StyleSuggestionModel for use in the app
    /// - Parameters:
    ///   - text: The original text that was analyzed (for position calculation)
    ///   - style: The writing style that was used
    /// - Returns: A StyleSuggestionModel, or nil if the original text wasn't found
    func toStyleSuggestionModel(in text: String, style: WritingStyle) -> StyleSuggestionModel? {
        // Find the position of the original text in the input
        guard let range = text.range(of: original) else {
            return nil
        }

        let startIndex = text.distance(from: text.startIndex, to: range.lowerBound)
        let endIndex = text.distance(from: text.startIndex, to: range.upperBound)

        // Build diff segments
        let diff = buildDiffSegments(original: original, suggested: suggested)

        return StyleSuggestionModel(
            id: UUID().uuidString,
            originalStart: startIndex,
            originalEnd: endIndex,
            originalText: original,
            suggestedText: suggested,
            explanation: explanation,
            confidence: 0.85,  // FM suggestions are high quality
            style: style,
            diff: diff
        )
    }

    /// Build diff segments showing what changed between original and suggested
    private func buildDiffSegments(original: String, suggested: String) -> [DiffSegmentModel] {
        // Simple diff: show original as removed, suggested as added
        // For more sophisticated diff, could use a proper diff algorithm
        var segments: [DiffSegmentModel] = []

        if original != suggested {
            segments.append(DiffSegmentModel(text: original, kind: .removed))
            segments.append(DiffSegmentModel(text: suggested, kind: .added))
        } else {
            segments.append(DiffSegmentModel(text: original, kind: .unchanged))
        }

        return segments
    }
}

@available(macOS 26.0, *)
extension FMStyleAnalysisResult {
    /// Convert all suggestions to StyleSuggestionModel array
    /// - Parameters:
    ///   - text: The original text that was analyzed
    ///   - style: The writing style that was used
    /// - Returns: Array of valid StyleSuggestionModel (filtering out any with invalid positions)
    func toStyleSuggestionModels(in text: String, style: WritingStyle) -> [StyleSuggestionModel] {
        suggestions.compactMap { $0.toStyleSuggestionModel(in: text, style: style) }
    }
}
