// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
typedef enum __swift_bridge__$ErrorSeverityTag { __swift_bridge__$ErrorSeverity$Error, __swift_bridge__$ErrorSeverity$Warning, __swift_bridge__$ErrorSeverity$Info, } __swift_bridge__$ErrorSeverityTag;
typedef struct __swift_bridge__$ErrorSeverity { __swift_bridge__$ErrorSeverityTag tag; } __swift_bridge__$ErrorSeverity;
typedef struct __swift_bridge__$Option$ErrorSeverity { bool is_some; __swift_bridge__$ErrorSeverity val; } __swift_bridge__$Option$ErrorSeverity;

void* __swift_bridge__$Vec_ErrorSeverity$new(void);
void __swift_bridge__$Vec_ErrorSeverity$drop(void* vec_ptr);
void __swift_bridge__$Vec_ErrorSeverity$push(void* vec_ptr, __swift_bridge__$ErrorSeverity item);
__swift_bridge__$Option$ErrorSeverity __swift_bridge__$Vec_ErrorSeverity$pop(void* vec_ptr);
__swift_bridge__$Option$ErrorSeverity __swift_bridge__$Vec_ErrorSeverity$get(void* vec_ptr, uintptr_t index);
__swift_bridge__$Option$ErrorSeverity __swift_bridge__$Vec_ErrorSeverity$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_ErrorSeverity$len(void* vec_ptr);
void* __swift_bridge__$Vec_ErrorSeverity$as_ptr(void* vec_ptr);

typedef struct GrammarError GrammarError;
void __swift_bridge__$GrammarError$_free(void* self);

void* __swift_bridge__$Vec_GrammarError$new(void);
void __swift_bridge__$Vec_GrammarError$drop(void* vec_ptr);
void __swift_bridge__$Vec_GrammarError$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_GrammarError$pop(void* vec_ptr);
void* __swift_bridge__$Vec_GrammarError$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_GrammarError$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_GrammarError$len(void* vec_ptr);
void* __swift_bridge__$Vec_GrammarError$as_ptr(void* vec_ptr);

typedef struct AnalysisResult AnalysisResult;
void __swift_bridge__$AnalysisResult$_free(void* self);

void* __swift_bridge__$Vec_AnalysisResult$new(void);
void __swift_bridge__$Vec_AnalysisResult$drop(void* vec_ptr);
void __swift_bridge__$Vec_AnalysisResult$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_AnalysisResult$pop(void* vec_ptr);
void* __swift_bridge__$Vec_AnalysisResult$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_AnalysisResult$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_AnalysisResult$len(void* vec_ptr);
void* __swift_bridge__$Vec_AnalysisResult$as_ptr(void* vec_ptr);

uintptr_t __swift_bridge__$GrammarError$start(void* self);
uintptr_t __swift_bridge__$GrammarError$end(void* self);
void* __swift_bridge__$GrammarError$message(void* self);
struct __swift_bridge__$ErrorSeverity __swift_bridge__$GrammarError$severity(void* self);
void* __swift_bridge__$GrammarError$lint_id(void* self);
void* __swift_bridge__$AnalysisResult$errors(void* self);
uintptr_t __swift_bridge__$AnalysisResult$word_count(void* self);
uint64_t __swift_bridge__$AnalysisResult$analysis_time_ms(void* self);
void* __swift_bridge__$analyze_text(void* text);


